### ISSUE TITLE
Issue with CoreOS Image clean flow

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#101]
when we run the flow we get : 
2015/04/13 13:46:27 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/04/13 13:46:27 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 1s
Error retrieving list of active machines: timeout reached

**Comment by meirwah** [comment]
@Bonczidai can you please look into that?

**Comment by meirwah** [comment]
adding @pavithragopisetty to this thread...

**Comment by Bonczidai** [comment]
Seems like fleet cannot connect to the other machines in the cluster. Can you run fleetctl lits-machines command? It should display the upper error message.

Make sure that you create the machines in the cluster with a valid (and the same) cloud config file.Some tips when creating droplets:

- the machines have to be in the same region: e.g Ams-3
- you can add cloud-config in user data field (enable user data)
- it is advised to enable private networking also

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-coreos-cluster-on-digitalocean

Does this solve the issue?

**Comment by meirwah** [comment]
Issue was Bad install of the cluster
