### ISSUE TITLE
circle.ci framework issue - port is already allocated for dind

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#133]
FATA[0000] Error response from daemon: Cannot start container 0c6b22866e14faf072f059d377e80918e315b5d41c3e835fae7878b48f495298: Bind for 0.0.0.0:49153 failed: port is already allocated docker run --privileged --lxc-conf="lxc.aa_profile=unconfined" -d -p 4444 -p 49153:22 -e PORT=4444 --name docker_host_ssh orius123/dind-ssh returned exit code 1

https://circleci.com/gh/CloudSlang/cloud-slang-content/308

**Comment by meirwah** [comment]
@orius123 WDYT? maybe diff port? maybe we do not clean well the dind?

**Comment by orius123** [comment]
Not sure. Maybe it run multiple tests on the same machine. I think we should get a random port each time and update the tests to know what it is somehow..

**Comment by meirwah** [comment]
Also can close this?

**Comment by orius123** [comment]
I guess we can..
