### ISSUE TITLE
Content system test coverage 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#155]
Tests (by priority):
- [x] containers @raskin-aleksandr 
  - [x] clear_container
  - [x] run_container
  - [x] create_db_container
  - [x] delete_container
  - [x] demo_clear_containers_wrapper
  - [x] get_all_containers
  - [x] get_container_ip
  - [x] start_container
  - [x] start_linked_container
  - [x] stop_container
- [x] images @orius123 
  - [x] clear_docker_dangling_images_flow
  - [x] clear_docker_images
  - [x] clear_docker_images_flow
  - [x] clear_unused_docker_images
  - [x] get_all_images
  - [x] get_dangling_images
  - [x] get_image_name_from_id
  - [x] get_image_parent
  - [x] get_used_images
  - [x] get_used_images_flow
  - [x] inspect_image
  - [x] pull_image
- [x] get_container_names @Bonczidai 
- [x] demo-dev-ops @Bonczidai (local machine #183 )
- [x] cAdvisor @Bonczidai
  - [x] evaluate_resource_usage (local machine)
  - [x] get_container_metrics_cAdvisor (local machine)
  - [x] get_machine_metrics_cAdvisor
  - [x] parse_cadvisor_container (local machine)
  - [x] parse_cadvisor_machine
  - [x] report_container_metrics_cAdvisor (local machine)
  - [x] report_machine_metrics_cAdvisor
  - [x] restart_container_base_on_usage (local machine)
- [x] coreos @Bonczidai (local machine)
  - [x] cluster_docker_images_maintenance
  - [x] get_machine_public_ip
  - [x] list_machines_id
  - [x] list_machines_public_ip
- [x] mysql @meirwah
- [ ] report_mysql_status @raskin-aleksandr
- [x] base (linux os ) @raskin-aleksandr 
  - [x] check_linux_disk_space
  - [x] restart_process
  - [x] restart_server
  - [x] restart_service
  - [x] validate_linux_machine_ssh_access
  - [x] ping_hosts
- [x] Jenkins - get_last_buildnumber @tudorlesan 
- [x] marathon @tudorlesan  
- [x] consul @tudorlesan 
- [x] openstack (look here for help: https://groups.google.com/forum/#!topic/docker-user/sPC-5rOKJOw)

**Comment by oritstone** [comment]
@meirwah we are missing from the list above:
- Docker maintenance
- Docker utils
-  Openstack
Do we want to test these as well?
I started adding the specific flows in each section. Do you want to order them by priority?

**Comment by meirwah** [comment]
Docker maintenance, I think is already covered 
Docker utils - just one op, which is covered in a larger flow from the maintenance
Openstack  is tricky, since there is no OpenStack image right now, and it's quite hard to build one...

It's by priority

**Comment by orius123** [comment]
@oritstone I'm un-able to add report mysql to travis. can we close this one?

**Comment by oritstone** [comment]
Yes
