### ISSUE TITLE
cslang builder - not enough log info

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#158]
Duplicate of #https://github.com/CloudSlang/cloud-slang/issues/290

we should find a way to access a more detailed log (similar to CLI log) when running cslang builder..

now if a flow fails we just get the result but it's difficult to debug the execution

opinions?

**Comment by meirwah** [comment]
why close?

**Comment by Bonczidai** [comment]
yeah, duplicate - my bad
