### ISSUE TITLE
we need to standardize flows outputs

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang-content#164]
sometimes it's called 
- `response`
- `return_result`
- `error_message`
- `message`

I suggest to go with `message` all along
@oritstone @meirwah @SamMarkowitz  WDYT?

**Comment by meirwah** [comment]
agree, we can use similar term to the one used in OO

**Comment by SamMarkowitz** [comment]
Yes, of the options you listed I agree that `message` has the best combination of clarity and universality.

**Comment by mihaitusa** [comment]
@lrevnic pls help me with some details... Thanks!

**Comment by mihaitusa** [comment]
The discussions had with @lrevnic showed that the effort will be significant.. we have to modify all the content... I will continue it offline.

**Comment by mihaitusa** [comment]
Discussions Summary: 
- We intend to keep only return_result and error_message; 
- The level of errors messages verbosity will be customizable only for logs; 
- We have to let go our snake_case naming convention and replace it with camelCase convention to get rid of tons inputs bindings and be aligned with Java @Actions.

**Comment by mihaitusa** [comment]
@meshipeer @Bonczidai @gituser173 @SamMarkowitz ... please add your observations on this issue...

**Comment by Bonczidai** [comment]
- can you give a specific example of an `@action` - how will the set of outputs change / look like? do you intend also to remove `return_code` - is that even possible?
- **please no camelCase / just no**

```
    - proxy_port:
        required: false
    - proxyPort:
        default: ${get("proxy_port", "8080")}
        private: true
```

the first binding shouldn't be costly, it does not need any Python evaluation -- please do a benchmarking on this. We recently had a big effort of moving everything to snake_case + developing the upper translation mechanism..

**Comment by mihaitusa** [comment]
Regarding the input binding I agree with @Bonczidai ... Isn't that bad...

**Comment by mihaitusa** [comment]
I don't think that we can get rid of returnCode right now....
