### ISSUE TITLE
use docker-py library instead of implementing all over SSH

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang-content#165]
Didn't see any C-extensions use but haven't tested that it works..
Looks mature enough. Can work locally using unix sockets or remote with docker http API.
@meirwah WDYT?

**Comment by meirwah** [comment]
not sure what you mean here...
you are talking about replacing the Java action of SSH , with Paramiko?

**Comment by orius123** [comment]
No. It's a python library that talks to docker through http

**Comment by orius123** [comment]
It can also talk through Unix sockets so you can run commands also locally. Also, I saw that there were small changes to the cli output between docker versions, talking through API is much safer.

**Comment by tethryus** [comment]
@meshipeer We prefer to implement a newer functionality using RESTful API in the docker integration.
