### ISSUE TITLE
check_linux_disk_space operation actual behavior different than expected ?

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#180]
`check_linux_disk_space` op is supposed to "Check the disk space percentage on a Linux machine"

current command:  df -kh | grep -v "Filesystem" | awk 'NR==1{print $5}'
current returned value: first line (red rectangle on the screenshot)
current behavior: disk space of the first listed filesystem

I would go with the following change:

command:  df -kh . | grep -v "Filesystem" | awk '{print $5}'
returned value: 5% (green rectangle)
behavior: disk space of the partition the current directory belongs to (the entry point for ssh)

![df](https://cloud.githubusercontent.com/assets/8058961/8109887/ebc5f8fc-1061-11e5-8641-3bc8df90c1fd.png)

WDYT?

**Comment by orius123** [comment]
Y don't we get the mount / partition as an input?
or take `root``/` if none given

**Comment by Bonczidai** [comment]
:+1:

**Comment by tudorlesan** [comment]
Solved by #207
