### ISSUE TITLE
Flow results used with expressions

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#182]
Consider io.cloudslang.docker.images.get_all_images which uses the ssh flow for command execution.

The **flow** contains results in operation style:

```
  results:
    - SUCCESS: return_code == '0' and (not 'Error' in standard_err) and (not 'command not found' in standard_err) and (not 'deamon' in standard_err)
    - FAILURE
```

the flow passes compilation time but the result expressions are not evaluated (flow ends with ssh task results)

**Comment by Bonczidai** [comment]
IMHO: this is serious issue - we should handle it ASAP - multiple flows suffer from this issue - they all finish with SUCCESS (because of the SSH success) even if they should **fail**

**Comment by orius123** [comment]
:+1:

**Comment by oritstone** [comment]
I'm fixing some of these flows in #191
The flows in which I also found this issue and didn't fix it yet are:
- openstack.utils.check_server
- docker.images.get_all_images

**Comment by orius123** [comment]
I think we should also fail compilation. So we need an issue at cloudlslang/cloud-slang as well

**Comment by oritstone** [comment]
@orius123 please open an issue about the compilation

**Comment by Bonczidai** [comment]
please note that only removing the result expressions will not be enough - we should find a solution to check the ssh return result (so the flow will not succeed anyway)

**Comment by oritstone** [comment]
In the flows that I already fixed, the expression for SUCCESS was the same as is already checked by the ssh_command, so the functionality did not change.
In the remaining flows, we need to find another solution

**Comment by Bonczidai** [comment]
:+1:
