### ISSUE TITLE
operation io.cloudslang.base.utils.sleep should have both SUCCESS and FAILURE results

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#219]
now it has only SUCCESS - script should be in a try-catch (e.g. user supplies an input that cannot be converted to float)

**Comment by oritstone** [comment]
I do not think we should have a failure result.
Failure is when the logics of he flow/operation resulted in failure.
Errors such as passing wrong type of input, or not passing required input are not a logical result of our executables but an unexpected error which we deal with sending an exception event
@meirwah, @orius123, WDYT?

**Comment by meirwah** [comment]
No , I think @Bonczidai iis right, error from the action should result in  FAILURE result

**Comment by oritstone** [comment]
@orius123 WDYT?

**Comment by orius123** [comment]
I think @oritstone is right. IMHO what you are suggesting is EXCEPTION, we talked about it a while ago, but we don't have this functionality yet. Plus, if we would implement it, I'm not sure the it should be with a result.

**Comment by meirwah** [comment]
still think it should be failure in that case..

**Comment by orius123** [comment]
@meirwah we can add it specifically to sleep op, but do we want to add it to the language behavior, that failure catches exceptions?

**Comment by meirwah** [comment]
@orius123  I do not think so...
I do not see this as a lang feature...

**Comment by orius123** [comment]
OK.. so we need to apply it to all of our content.
what about exceptions from inputs or outputs expressions? it has to be a language feature if we want to be consistent for all cases.

**Comment by tethryus** [comment]
Fixed in pull request #650
