### ISSUE TITLE
Solution to flow result evaluation problem - when using ssh flow

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#236]
Should find a solution to result evaluation problem in case of recently promoted operations that are now flows and use the SSH flow - usually we need to check if some keywords are found in the return result (or stdout stderr etc.)

Now we have to add multiple tasks to check the occurrences of such strings - need a more elegant way

maybe add a checking feature to the SSH flow or add an operation that can search for multiple keywords in a string (this way we need only one task to check the result)

other ideas, opinions?

**Comment by orius123** [comment]
I agree that this an issue. but don't you think that we should solve it with a language feature instead of content one?

**Comment by Bonczidai** [comment]
:+1:  may be a good idea - we will need to do a brainstorming to hear everybody's opinions on this

**Comment by oritstone** [comment]
I think that #420 is improving the situation

**Comment by Bonczidai** [comment]
CloudSlang/cloud-slang#569 will solve this issue

**Comment by tethryus** [comment]
This is a feature that will be handled at language level.
