### ISSUE TITLE
remove io.cloudslang from content nemaspaces

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang-content#252]
it just make stuff longer

**Comment by oritstone** [comment]
@meirwah, @Bonczidai WDYT?

**Comment by Bonczidai** [comment]
I agree - cannot see any important advantage of it

**Comment by meirwah** [comment]
same as Levi...

**Comment by meshipeer** [comment]
i think its make it visible that this content came from cloudslang
