### ISSUE TITLE
Git flows - need feedback

### ISSUE THREAD

**Issue by lirantal** [CloudSlang/cloud-slang-content#277]
Hey guys,

So we have a few basic flows already:
1. Git clone
2. Git pull + checkout
3. Git status (to check whether a git repo is clean or dirty)
4. Git reset (to clean a working git repo in case it's dirty)

What other flows do you think we need to push in to cover more git related actions?
I know there are the obvious git's "add", "commit", "merge" but I doubt any of these actions will be performed in an automated way, with the exception of "git merge" where actually I do think of a continue-integration flow that can be connected here which for example merge development branch with master after a testing flow was finished.

So let me know what you think :)

**Comment by meirwah** [comment]
I think it's enough for now for Git content...

How about adding some other content? from our roadmap (https://github.com/CloudSlang/cloud-slang/wiki/Project-Roadmap )?

**Comment by orius123** [comment]
I think that git merge, fetch and maybe push are also basics.
In addition what about more options for status / git log?

**Comment by lirantal** [comment]
@meirwah I'll definitely take a look there and choose something nice to add up
@orius123 yep I think the same, I'll add merge and fetch, not sure if push is of any relevancy though. Why would someone want to run a flow that performs a  'git log'? and which other options do you think are necessary for status?

Thanks for chiming in guys, I really appreciate it! :)

**Comment by orius123** [comment]
- Regarding push I thought of a CI use-cases where you clone a branch, run tests and f it passes you push it to master / stable branch. (gerrit style..)
- for the above use-case maybe create branch is also important
- git status has different formatting.
- git log for data when stuff goes bad, bur I agree that it's weaker..

**Comment by lirantal** [comment]
I think we can agree to implement further the merge, fetch and push.
I might also send updates to the "git checkout" flow to support creating a new branch etc (although I believe newer git versions do that by default IIRC)

**Comment by orius123** [comment]
`checkout -b` create new branch just checking out branch will live you headless

**Comment by lirantal** [comment]
Not entirely true, if the branch already exist then I can just checkout to it, the -b is only when I need to create the branch. With the flow we have today the -b isn't a must, so that you can run just the git_status_flow on an already pulled/cloned git working directory.

**Comment by lirantal** [comment]
I opened PR https://github.com/CloudSlang/cloud-slang-content/pull/349 for git_fetch and I'll submit another one for git_merge and we can probably close the git saga for now as we have all the basic functionality for creating git related flows and continue with another theme.

I suggest we can close this brainstorming session for git flows.

**Comment by meirwah** [comment]
:+1:
