### ISSUE TITLE
Sanity check for build env droplets

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#285]
make sure there are no zombie droplets

**Comment by Bonczidai** [comment]
1 possibility: use Cron to periodically run a CloudSlang flow which removes droplets that:
- match the name of `ci-{build number}-coreos-{number}`
- created more than 2 hours ago

**Comment by meirwah** [comment]
where the CRON runs? which env? machine? another DO droplet?

**Comment by Bonczidai** [comment]
Wee need for Cron a Linux machine with CloudSlang installed on it -- which can be another DO droplet

**Comment by meirwah** [comment]
Another option is to use OO (it has a scheduler) on DO or Lab machine...

**Comment by orius123** [comment]
There are a lot of cron free services. Don't think you need OO for this.

**Comment by meirwah** [comment]
https://www.cronasaservice.com/

**Comment by meirwah** [comment]
but it might be a good example of using OO ... eating you own ...

**Comment by orius123** [comment]
I fear it might be more of 'maintaining your own...'
