### ISSUE TITLE
Add blog / readme / doc on CircleCI / Travis build env

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#287]

**Comment by Bonczidai** [comment]
I think we should do 2 separate blogs on the build system:
- Travis: Docker in Docker (use cases: SSH, Docker)
- CircleCI: using a PaaS provider to host machines (use cases: default, CoreOS, Swarm etc.)

We can talk about the differences: Travis (legacy system with VMs), CIrcleCI (uses Docker containers for build machines - no `--privileged` (dind) mode but much faster), defining a matrix (simpler syntax on Travis but more flexible on CircleCI) and so on..

Here a sketch for the CircleCI blog:

- intro about CI, CloudSlang (flows, builder tool), why we need this
- logical flow of events (push -> circleci build starts -> cmds in circle.yaml -> droplet startup ....)
- explain the important aspects, the variety of technologies we combine
- using parallelism, distribution of commands on build machines
- sensitive data management: env variables

p.s. imagine nice illustrations and screenshots everywhere

**Comment by meirwah** [comment]
:+1: , @orius123 @SamMarkowitz  WDYT?

**Comment by Bonczidai** [comment]
.. and I think that we should handle #291 (minor issue) before the blog goes online since the droplet names will probably appear in the blog

**Comment by orius123** [comment]
I think we should do it a series of two or three blogs:
maybe:

1. How we write content tests (builder and stuff)
2. Circle ci
3. Travis
