### ISSUE TITLE
Add setup_marathon use case to content

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#289]
now it is under `tests` - sets up a sample marathon env on a single Docker host ( according to http://viralkitty.com/marathon-and-docker/ )

it could be part of the actual content - WDYT?

**Comment by meirwah** [comment]
sounds fine, it runs on DO or Travis/cricleCI infra?

**Comment by Bonczidai** [comment]
DO - currently on a CoreOS machine
