### ISSUE TITLE
CircleCI build problems

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#302]
List of (sporadic) build problems on CircleCI:

- [ ] memory limit exceed: https://circleci.com/gh/CloudSlang/cloud-slang-content/1412
- [x] branch name (will be fixed in #291): https://circleci.com/gh/CloudSlang/cloud-slang-content/1411
- [ ] session is down (probably ssh action bug): https://circleci.com/gh/CloudSlang/cloud-slang-content/1381
- [ ] test_create_marathon_app_success - Connect to 188.166.72.10:8888 [/188.166.72.10] failed - https://circle-artifacts.com/gh/CloudSlang/cloud-slang-content/1415/artifacts/1/home/ubuntu/cloud-slang-content/builder.log

**Comment by orius123** [comment]
I think we should open an issue for first and third.

**Comment by oritstone** [comment]
@Bonczidai please open separate issues

**Comment by Bonczidai** [comment]
opened issues for the relevant ones
