### ISSUE TITLE
demo_dev_ops network issue on 0.8

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang-content#307]
I tested demo_dev_ops.sl on Windows on different HP networks and on one of our remote Docker machines and in each case the last step (test_application) times out, possibly because of a proxy. The application is actually up and can be checked from the browser though. 

Also, because this step fails, send_error_mail step should be executed, which concatenates a string with the output of test_application which was renamed from error_message to output_message so then the flow throws a Slang Error. I already fixed this though it's not merged to 0.8 but to master.

**Comment by oritstone** [comment]
@gituser173 please check if it still happens

**Comment by Bonczidai** [comment]
move this issue to this sprint from backlog? @oritstone

**Comment by gituser173** [comment]
The issue can be reproduced, test_application times out, but it cannot be accessed through the browser.

**Comment by gituser173** [comment]
Works after adding swap file on CoreOS host. Here is the tutorial on how to add the swap file(use the The Faster Way): https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
