### ISSUE TITLE
Add VMware content [4]

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#311]
basic VMware ops

**Comment by mihaitusa** [comment]
We will use latest VMware SDK.

**Comment by mihaitusa** [comment]
The Create VM is ready/functional... remaining the jar issue...

**Comment by mihaitusa** [comment]
related to PR #86

**Comment by mihaitusa** [comment]
Until now we have: CreateVM, DeleteVM, PowerOnVM, PowerOffVM

**Comment by mihaitusa** [comment]
- [x] Create VM ; 
- [x] Delete VM; 
- [x] Power On VM; 
- [x] Power Off VM

**Comment by mihaitusa** [comment]
In order to have an basic CRUD (CreateReadUpdateDelete) scenario we also need: 
- [ ] Update VM (customization); 
- [ ] List VM's; 
and the next 2 operations (first needed for Create VM and the next one because is important): 
- [ ] Get OS Descriptors; 
- [ ] Clone VM.
