### ISSUE TITLE
PowerShell operations 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#313]
Add basic PowerShell operations

**Comment by meirwah** [comment]
@gituser173  please write down here diff possibilities of Libs (Java/Python) we can use for US...

**Comment by meirwah** [comment]
look at this : 
https://github.com/xebialabs/overthere
https://pypi.python.org/pypi/pywinrm

**Comment by gituser173** [comment]
j-Interop: http://www.j-interop.org/index.html

**Comment by gituser173** [comment]
pull request: PowerShell Script #378
