### ISSUE TITLE
CircleCI build problem 1: memory limit exceed [1]

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#317]
https://circleci.com/gh/CloudSlang/cloud-slang-content/1412

**Comment by Bonczidai** [comment]
btw in this case we get zombie droplets (#285)

**Comment by meirwah** [comment]
maybe we should handle zombie droplets sooner ...

**Comment by orius123** [comment]
: +1:

**Comment by Bonczidai** [comment]
not reproduced in the last 10 builds -- let's see if ti happens in future builds

**Comment by meirwah** [comment]
ok.. so closing this...

**Comment by Bonczidai** [comment]
happens again: https://circleci.com/gh/CloudSlang/cloud-slang-content/1995
