### ISSUE TITLE
VMware vSphere template cloning with customization for the Guest OS Customization Specifications

### ISSUE THREAD

**Issue by nuxclass** [CloudSlang/cloud-slang-content#339]

**Comment by mihaitusa** [comment]
It seems that the customers wants to have an input to provide a specific customization template/file (xml format) as a part of Clone VM operation.

**Comment by mihaitusa** [comment]
We need: 
- [ ] Clone VM. 

Clone VM was moved here from #311.

**Comment by mihaitusa** [comment]
@Bonczidai You can close this. The above functionalities are enough to supply a valid scenario for this request (open source of course).

**Comment by Bonczidai** [comment]
agree 👍 thanks @mihaitusa @tethryus
