### ISSUE TITLE
Missing ops in base folder

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#342]
-	math comparisons. With strings the situation is pretty good.
-	file read operation should include option of reading line by line
-	Parse JSON, get key, get value, etc…
-	XML processing
-	List iterators for csv,json,xml
-	LDAP (search, add, update, some sample flows)
-	File system – iteration sample (directory tree traverse)

**Comment by oritstone** [comment]
@meirwah please devide to several issues

**Comment by meirwah** [comment]
splitted to many issues...
