### ISSUE TITLE
Parse JSON, get key, get value, etc…

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#359]

**Comment by benc-uk** [comment]
Suggestion, that you look at JSONPath https://pypi.python.org/pypi/jsonpath-rw which is a general purpose syntax for querying, extracting JSON data. It is equivalent to XPath

**Comment by oritstone** [comment]
Add operations for:
- Get Object Keys
- Get Value from Object
- Get Array Entry
- Add JSON Property to Object
- Add Object to Array
- Add Property to Object
- Add to Array
- Array Size
