### ISSUE TITLE
Default values on inputs

### ISSUE THREAD

**Issue by mihaitusa** [CloudSlang/cloud-slang-content#368]
When we have an required input and we provide value for it using an inputs file then: "Command failed java.lang.RuntimeException: java.lang.RuntimeException: Error tra
nsforming source: test_CRUD_application.sl to a Slang model. null".

**Comment by mihaitusa** [comment]
@Bonczidai Try it with OpenShift content - create application and don't provide any value for host.

**Comment by Bonczidai** [comment]
this issue refers to the fact that after changing the DSL, task arguments are not required (can be null) - situation is:

```
- input:
    required: false
```

-> 

```
- input
```

which works with latest build from master -- cannot reproduce
