### ISSUE TITLE
get_authentication.sl operation and get_authentication_flow.sl usage is too limited

### ISSUE THREAD

**Issue by chronical** [CloudSlang/cloud-slang-content#4]
the get_authentication operation and the get_authentication_flow should be generalized (with default naming for inputs/results , maybe moved ot the base subfolder) as it should not only serve the openstack scenario.

**Comment by meirwah** [comment]
can you elborate which inputs/outputs you think should be there?
and to which other systems you want to use them?

**Comment by chronical** [comment]
i will give you as an example the integration in the project that we want to build. we would like to create a authentication flow, very similar to the openstack one, which will serve the authentication mechanism for an artifact repository. I would be easier for us if we could re-use a more general authentication flow (with its operation) and just extend it for re-usability.

eg: 
1. on the flow level
generalize openstack_content.get_authentication:
          - host: openstackHost
          - identityPort: openstackIdentityPort
          - username: openstackUsername
          - password: openstackPassword

2. on the operation level: generalize/open for customization the rest call URL

**Comment by meirwah** [comment]
@chronical  auth with which systems/API? 
we have general SSH+REST flows/ops, how is this diff?

**Comment by Bonczidai** [comment]
I think this issue was closed accidentally by the upper commit - **all**, please be careful what you put into commit messages, don't use `#{number}` syntax if you don't have to, so you will not create references by mistake -- @mihaitusa @gituser173

@oritstone please reopen issue if this is the case

**Comment by chronical** [comment]
issue was solved with a different implementation (there is now specific authorization or each integration)
closing
