### ISSUE TITLE
http_client_post - auth_type should be optional

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/cloud-slang-content#400]
Hello,

It seems that http_client_post operation was recently changed and auth_type/query_param parameters were added as optionnal inputs. Unfortunately, it's not the case and it broke all older operations.
```
Command failed java.lang.RuntimeException: Slang Error : Error running: http_cli
ent_action_post: Input with name: 'authType' is Required, but value is empty
```

```
Command failed java.lang.RuntimeException: Slang Error : Error running: http_cli
ent_action_post: Input with name: 'query_param' is Required, but value is empty
```

I think we should configure following in the low level operations
```
    - auth_type:
        default: "'basic'"
        required: false
```

```
   - query_params:
        default: "''"
        required: false
```
I am not sure if it's the java action which require this parameter or it's something else.

Could someone confirm this issue ? You can use my workflows in https://github.com/mbettan/cloud-slang-content/tree/master/content/io/cloudslang/nutanix to try

Thanks very much

**Comment by mbettan** [comment]
```
    - auth_type:
        default: "'basic'"
        required: false
```

```
   - query_params:
        default: "''"
        required: false
```

**Comment by Bonczidai** [comment]
the behavior you observe could be related to the task arguments change in the DSL ( https://github.com/CloudSlang/docs/pull/19/files ) - task arguments (inputs) does not support any modifier now:

correct:
```
Task:
  - key
  - key: value
```
incorrect:
```
task:
  - key:
      default: value
      required: false
```

please use the latest version of content and builder / CLI ( https://github.com/CloudSlang/cloud-slang/releases/tag/cloudslang-0.8.5 ) and let us know whether the problem still persist

**Comment by oritstone** [comment]
@mbettan did it solve your problem?

**Comment by oritstone** [comment]
We are closing the issue
@mbettan if you have additional problems further on ,please open an issue
