### ISSUE TITLE
Content problems encountered when reviewing comments in base, consul and coreos folders

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang-content#47]
+ general comments
    + inconsitent in whether input type error checking is present or whether the types are assumed to be correct
+ base
    + comparisons
        + less_than_percentage
            + failure result not working in error condition
    + files - message = `sys.exc_info()[0]` does not give usable information
        + copy
            + failure case has message of copying done successfully
        + delete
            + Succes message is - source + ' was removed'
        + read_from_file
            + uses stringified booleans
        + write_to_file
            + uses stringified booleans
            + prints message instead of using an output
        + zip/unzip
            + input usage is inconsistent - archive_name is the file name in one and the full path in the other
            + maybe default output to the same directory as the input 
    + network
        + rest
            + http_client_action
                + move method input up to top under url?
        + verif_app_is_up
            + result is testing stringified version of boolean
    + strings
        + match_regex
            + uses stringified booleans
        + string_occurrence_counter
            + results not working due to usage of stringified int 
    + utils
        + random_number_generator
            + failure result not working in error condition
+ consul
    + parse_key
        + uses stringified ints

**Comment by meirwah** [comment]
@SamMarkowitz regarding : 

verif_app_is_up
result is testing stringified version of boolean

I do not think it's a bug.. it will work in both cases.. am i wrong?

**Comment by meirwah** [comment]
@SamMarkowitz  please open a new issue on : 
comparisons
less_than_percentage
failure result not working in error condition

and assign @tudorlesan on it...

**Comment by SamMarkowitz** [comment]
Correct. It will work both ways.

**Comment by orius123** [comment]
@meirwah @SamMarkowitz @raskin-aleksandr @tudorlesan 
is this fixed?
on what branch?
