### ISSUE TITLE
Comments from proofing docker folder

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang-content#49]
+ general
    + file naming: inconsistent as to whether folder name is assumed or not (e.g. get_all_images vs. clear_docker_images)
    + optional parameter with `default`: inconsistent as to whether `required: false` is also present
    + some flows do not have explicitly declared and documented results 
+ docker
    + images
        + unlike other folders, contains operations and flows with the same name except flow has the word "flow" appended 
    + maintenance: should this be renamed to "mysql"
        + diskspace_health_check : should this be in the linux folder?
        + check_mysql_is_up: shouldn't `command` be `overridable: false`

**Comment by meirwah** [comment]
adding @tudorlesan and @Bonczidai
