### ISSUE TITLE
New folder structure for content

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#501]
current folder structure for content has inconsistencies - e.g. PaaS folder, but no IaaS for OpenStack

we should think about a folder structure that better reflects the content

**Comment by mihaitusa** [comment]
IMHO the differences between the PaaS, IaaS and SaaS are not very clear established. Everybody can have an good argument if "X" solution is PaaS or rather IaaS ... and so on. So, to avoid any conceptual/high level arguments, probably is better to rename the "cloud_provider" folder to be simplier "cloud" and let there: Amazon, Digital Ocean, Google Container Engine, HP Cloud and put there as well OpenStack, Heroku, OpenShift and Stackato. Of course the VMware should be much better to stay alone under the "virtualization" folder. @Bonczidai @gituser173 @meshipeer @SamMarkowitz WDYT about it?

**Comment by mihaitusa** [comment]
@mbettan  Please give feedback on this ... Thanks!

**Comment by mihaitusa** [comment]
@lrevnic  Please share your expertise on this... Thanks!

**Comment by mbettan** [comment]
Sorry - I disagree, it's clear for people that PaaS providers are Heroku, OpenShift, Stackato, Google App Engine, ...

You can probably do something like
Cloud\IaaS\Amazon
Cloud\PaaS\OpenShift
...

**Comment by Bonczidai** [comment]
we need to think here about the whole repository - the structure should be general enough to support flexibility

regarding cloud: yepp, we can do IaaS/PaaS/SaaS.. if we want to structure after service model (is it good enough?)

maybe something like this? -
```
- base
- infrastructure_management (Chef)
- cloud (....)
- virtualization (VMware)
- monitoring (Consul)
- containers (Docker)
- orchestration (OO)
- scripting (Powershell)
```

.. maybe does not worth to create high level folders (it's arguable), but at least the **cloud related** folders need to be rearranged

**Comment by remusgolgot** [comment]
I think the main issue is that the root folder names are currently both solution names ( paas ) , product names ( chef, openstack .. ) , technology names ( powershell ) and some other generic names ( base, cloud_provider )

I would have a similar approach to what we have now in the OOTB content. ( really close to what Levi said in the previous comment + probably move "scripting" under "base" - keeping everything not integration related under base makes more sense )

This way, we would keep the alignment with OOTB ( easier for the users to consume and build their own & easier for us to migrate content from one place to the other and maintain the whole thing consistent )

**Comment by lrevnic** [comment]
For the sake of simplicity I vote for having one 'cloud' folder for now. 
In the future we may split it in cloud/iaas, cloud/paas and cloud/saas

**Comment by mihaitusa** [comment]
@lrevnic I agree... for now. This is what I proposed in the first place.

**Comment by mbettan** [comment]
I agree for starting point

**Comment by mihaitusa** [comment]
First of all thanks to everyone for the feedback. We have a conclusion regarding the new content folder structure, it will look like this: 
- cloud
  - heroku; 
  - openshift;
  - openstack; 
  - stackato;
  - `<unchanged>`
- Virtualization (NEW):
  - vmware
- base
  - powershell
  - `<unchanged>`
- `<unchanged>`

In the future, when we grow on cloud content will split the "cloud" folder in:  cloud/iaas, cloud/paas and cloud/saas and of course we move the existing content accordingly.
