### ISSUE TITLE
WMI – this is very popular technology to integrate with different Microsoft products

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang-content#520]

**Comment by tethryus** [comment]
@Bonczidai Since the operation powershell_script.sl has been implemented, do a better WMI integration in order to use different Microsoft products? WDYT?

**Comment by mihaitusa** [comment]
@Bonczidai IMHO the implementation provided by @george-giloan in powershell module should be enough to cover a lot of scenarios...

**Comment by Bonczidai** [comment]
👍

**Comment by tethryus** [comment]
@Bonczidai Can this issue be closed if the operation meets all the requirements?

**Comment by Bonczidai** [comment]
yes, go for it
