### ISSUE TITLE
Enhance VMware CreateVM

### ISSUE THREAD

**Issue by mihaitusa** [CloudSlang/cloud-slang-content#538]
Enhance VMware CreateVM in order to support creation in specified resourcePool and specified folder with fallback mechanism - same as CloneVM.

**Comment by gituser173** [comment]
@mihaitusa also refactor the VMService class

**Comment by mihaitusa** [comment]
@gituser173  @meshipeer  I will refactor CreateVM && CloneVM and put somwhere else the helpers for the methods within VmService.

**Comment by mihaitusa** [comment]
Enhance VMware to support resourcePool && folderName, with fallback mechanism, refactor VmService and unit tests as we discussed.
