### ISSUE TITLE
Enhancement: flow to delete all the logs of containers

### ISSUE THREAD

**Issue by lirantal** [CloudSlang/cloud-slang-content#541]
Hi,

I was thinking of taking on a PR which adds a flow that deletes logs for containers (as those usually get big):

``` bash
rm /var/lib/docker/containers/*/*.log
```

That would be run on the docker host of course.

WDYT?

**Comment by Bonczidai** [comment]
:+1:

**Comment by lirantal** [comment]
@andel7 interested to join me on this?

**Comment by tethryus** [comment]
@lirantal Still interested in implementing this? I would like to join.

**Comment by lirantal** [comment]
Maybe I'll be getting back to that later. You're welcome to start working on it though, I'd be happy to review and take a look.
