### ISSUE TITLE
http_client_action fail with 'valid_http_status_codes' is not defined

### ISSUE THREAD

**Issue by dashapaster** [CloudSlang/cloud-slang-content#570]
i try to use http_client_post.sl  in my workflow :

rest.http_client_post:
             - url: "http://petstore.swagger.io/v2/pet"

and i get this error:
Command failed java.lang.RuntimeException: Slang Error: Error running: 'http_client_action'.
    Error evaluating result: 'SUCCESS',
    Error is: Error in running script expression: 'returnCode == '0' int(statusC
ode) in valid_http_status_codes',
    Exception is: ("no viable alternative at input 'int'", ('<string>', 1, 18, "
returnCode == '0' int(statusCode) in valid_http_status_codes\n"))

**Comment by Bonczidai** [comment]
I don't think the action (java method has this input) - the operation fails right?

could you please also provide here the details about the execution (inputs, CLI cmd) / log?

**Comment by dashapaster** [comment]
@Bonczidai  sure. is it ok now?

**Comment by Bonczidai** [comment]
:+1: 

please the expression on master: https://github.com/CloudSlang/cloud-slang-content/blob/master/content/io/cloudslang/base/network/rest/http_client_action.sl#L324

in you example seems that you are missing an `and` before the `int()` function

**Comment by dashapaster** [comment]
@Bonczidai  yes, you are right. But I put an `and`. it didn't help :(

Command failed java.lang.RuntimeException: Slang Error: Error running: 'http_cli
ent_action'.
    Error evaluating result: 'SUCCESS',
    Error is: Error in running script expression: 'returnCode == '0' and int(sta
tusCode) in valid_http_status_codes',
    Exception is: name 'valid_http_status_codes' is not defined

**Comment by Bonczidai** [comment]
does it work with CS v0.9.51?

**Comment by dashapaster** [comment]
@Bonczidai i'll check. i use CS v0.9.50

**Comment by dashapaster** [comment]
@Bonczidai  it starts to work. after i run it with  CS v0.9.51! cool) thank you for answer

**Comment by Bonczidai** [comment]
I think we can close this issue - caused by https://github.com/CloudSlang/cloud-slang/issues/568
