### ISSUE TITLE
Username input not required inconsistency

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cloud-slang-content#578]
For the following operations, the 'username' input is not required, while the 'password' input is required and other operations (e.g. create_virtual_machine) have both as required:

1. delete_virtual_machine 
2. get_virtual_machine_details 
3. list_virtual_machines_and_templates
4. power_off_virtual_machine 
5. power_on_virtual_machine

**Comment by mihaitusa** [comment]
fixed in https://github.com/CloudSlang/cloud-slang-content/pull/561

**Comment by mihaitusa** [comment]
@dumagalex Please confirm it!

**Comment by dumagalex** [comment]
@mihaitusa Confirming that the 'username' input is not set as required for the above reported operations

**Comment by mihaitusa** [comment]
@dumagalex I mean to confirme the bug is fixed in the latest zip with updated .sl files that I sent you....

**Comment by dumagalex** [comment]
Yes, the bug is fixed in the latest .sl files

**Comment by dumagalex** [comment]
@mihaitusa Please do this fix for samples/virtual_machine_lifecycle.sl
