### ISSUE TITLE
Timezone init wrong at customize_windows_guest

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cloud-slang-content#590]
Steps to reproduce:
1. Run customize_windows_guest only with the required inputs (do not give a value to \timezone')

Expected Result:
1. The operation runs successfully

Actual result: 
The operation returns a 'com.sun.xml.internal.ws.fault.ServerSOAPFaultException' error
while vSphere gives a 
'A specified parameter was not correct: Timezone' error

**Comment by mihaitusa** [comment]
@dumagalex Corrected accordingly with https://technet.microsoft.com/en-us/library/ms145276%28v=sql.90%29.aspx

**Comment by mihaitusa** [comment]
Fixed in https://github.com/CloudSlang/score-actions/pull/104/commits/20911f62873b57428ba40403c1000c47912ed4ce

**Comment by mihaitusa** [comment]
@dumagalex Please let me know when the fix is confirmed.

**Comment by dumagalex** [comment]
Confirming this has been fixed: the operation runs with result: Success when minimal inputs are provided (no timezone) against vSphere 4.1, 5.1 and 6.0
