### ISSUE TITLE
There is no remote command execution except SSH

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#591]
example of other needs: cannot target studio author machines to checkout repos thus get machines ready for classes for instance

by @andreivasiletruta -- could you please note here what other protocols you mean?

**Comment by andreivasiletruta** [comment]
I was thinking for instance to WMI

**Comment by tethryus** [comment]
Right now, there is a new remote command execution operation, powershell_script.sl located in the scripts folder

**Comment by tethryus** [comment]
@Bonczidai Do we need more than just powershell_script.sl to consider that we have more than one other remote command execution? WDYT?

**Comment by Bonczidai** [comment]
from my POV it's ok - @andreivasiletruta WDYT?

**Comment by andreivasiletruta** [comment]
Considering the additions, I consider it is ok. Issue could be closed

**Comment by tethryus** [comment]
Thank you all for your feedback, issue closed.
