### ISSUE TITLE
customize_windows_guest 'Cannot complete customization'

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cloud-slang-content#594]
Steps to reproduce:
1. run customize_windows_guest.sl using CS 9.52 CLI on rosvc5, using the following inputs:
virtual_machine_name: "OO1060"
computer_name: "OO1060-8195"
computer_password: "B33f34t3r"
owner_name: "Windows User"
owner_organization: "HPE"
ip_address: "16.77.8.105"
   (available IP initially assigned to another VM which is then powered off)
subnet_mask: "255.255.240.0"
gateway: "16.77.0.1"
timezone: "0"

Expected result: The operation runs successfully and the IP is changed

Actual result: 
The operation fails with
"Operation outputs:
- error_message = com.vmware.vim25.CustomizationFaultFaultMsg: Cannot complete customization.
- return_result = com.vmware.vim25.CustomizationFaultFaultMsg: Cannot complete customization.
- return_code = -1"

**Comment by mihaitusa** [comment]
Fixed in https://github.com/CloudSlang/score-actions/pull/104/commits/cbed97b2becf3e4a0028ac597eca39cb6a23e4c7

**Comment by mihaitusa** [comment]
@dumagalex Please let me know when the fix is confirmed.

**Comment by dumagalex** [comment]
The issue is fixed: customize_windows_guest.sl runs to result: Success without the reported error on vSphere 4.1, 5.1 & 6
