### ISSUE TITLE
Index input not used in remove_object_from_json_array

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang-content#618]
I don't think the `index` input works in the `remove_object_from_json_array` operation. Seems like there is an `index = None` that was left in by accident.

        ...
        index = None
        if index is None:
         decoded_json_array.remove(decoded_json_object)
        else:
         index=int(index)
         decoded_json_array.pop(index)
        ...

**Comment by mihaitusa** [comment]
@SamMarkowitz  The issue was fixed/merged in  JSON - Remove Object From Json Array #633 ... So, I close this issue...
