### ISSUE TITLE
SSH Operations problem

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang-content#66]
We have a a lot of operations which use SSH that are hard to use for someone using Slang the first time.
Operations like get_container_ip.sl would have the user expect that in the db_IP output would be an actual IP, but that's not the case only if the operation is used in a flow along side with the validate_linux_machine_ssh_access. Otherwise the Linux welcome message will be in that output. 

Will there be some kind of documentation on how to use those, or some kind of parser should be made, or maybe move all these kind of operations in util folders and provide the user only wrapper flows around them? Also, operation which seems generalized contains "db_IP" output as used for the demo_dev_ops.sl

WDYT @oritstone @meirwah

**Comment by meirwah** [comment]
db_IP name is wrong.. it's a bug.. it should container_ip
Linux welcome message is specific with a Linux distro of ubuntu (version 14.04)

And yes we will have example flows (like done in OO content) to show how to use ops in flows

**Comment by meirwah** [comment]
@tudorlesan please comment on this...

**Comment by tudorlesan** [comment]
I think I changed db_IP to container_ip and since you said everything else is documented, I'm fine with that :). I think this can be closed

**Comment by meirwah** [comment]
Please verify flow works...

**Comment by tudorlesan** [comment]
I made this change long ago. checked it a few times since then.
