### ISSUE TITLE
Base - Parse date

### ISSUE THREAD

**Issue by alinaciobanca** [CloudSlang/cloud-slang-content#682]
The operation does not parse the date and time correctly:
1) if the input is only a date (without time) -> the result is the date one day before the given date
2) if the input is only time (without date) -> the result is 2 hours earlier
3) if the input is date+time and you want to parse only the time -> the result is 3 hours earlier than the given time
4) if the input is date+time and you want to parse both of them -> the result is 3 hours earlier

**Comment by tethryus** [comment]
Fixed in #697
