### ISSUE TITLE
Amazon AWS EC2 - Implement Run Instances operation using QueryApi call

### ISSUE THREAD

**Issue by mihaitusa** [CloudSlang/cloud-slang-content#692]
Enhance Run_Instance_in_Region operation to take full advantage of TemplateOptions settings (inputs related to BlockDeviceMapping, SecurityGroups, KeyPair, Tag's, Network, etc) to be aligned to CSA flows requirements

**Comment by mihaitusa** [comment]
We can provide a useful workaround to the issue mentioned in #717 Amazon AWS EC2 - Network

**Comment by mihaitusa** [comment]
Solution to this enhancement is to implement fully functional operation using AWS Query API like into Create Volume, Attach Network Interface and Detach Network Interface and stop using jclouds for it.

**Comment by mihaitusa** [comment]
It seems that the solution for all problems (lack of proxyUsername && proxyPassword) will be covered when we will use exclusively QueryAPI.

**Comment by mihaitusa** [comment]
@Bonczidai  Close this PR because Run Instances is already part of the content (sl file)

**Comment by Bonczidai** [comment]
iof that's the case, you can close it @tethryus

**Comment by tethryus** [comment]
PR has been merged https://github.com/CloudSlang/cloud-slang-content/pull/850 Issue can be closed. Great work everyone. 
May the force be with you. Always
