### ISSUE TITLE
SSH Command operations does not close connection at the end of the flow

### ISSUE THREAD

**Issue by ralucatemle** [CloudSlang/cloud-slang-content#781]
When using ss_command.sl in a cs flow ,with input close_session= false (@input close_session: optional - if 'false' the SSH session will be cached for future calls of this operation during the
#!                       life of the flow, if 'true' the SSH session used by this operation will be closed
#!                       Valid: true, false - Default: false
) the connection is still open at the end of the flow

**Comment by lucian-cm** [comment]
this is nothing that can be handled at operation level, this should be handled by flow logic
