### ISSUE TITLE
decomision "cloud" folder

### ISSUE THREAD

**Issue by lrevnic** [CloudSlang/cloud-slang-content#845]
"cloud" term is generic and we can group inside it many integrations IaaS, SaaS, PaaS, Monitoring, Remediation etc.  This means we'll soon reach to have significant number of integrations inside the "cloud" folder/namespace.

proposal here is to move the integrations that are currently under "cloud" one level up thus to have the folder structure like:
/
-base
-amazon ec2
-microsoft azure 
-vmware vcenter

**Comment by andreivasiletruta** [comment]
@lrevnic I think moving up sounds reasonable. why not something like below?!
-base
-amazon 
   -ec2
   -…
-microsoft
   -azure
   -…
-vmware 
   -vcenter
   -…

**Comment by lrevnic** [comment]
@andreivasiletruta, if in the above proposal ec2 is under amazon folder (as a subfolder) that is an option as well; probably a better one for long term when there will be more integrations

**Comment by chronical** [comment]
@lrevnic @andreivasiletruta I would go with the top level vendor folders and in their subfolders include the flavous/products (eg: amazon/ec2;amazon/s3;amazon/rds;)

**Comment by lrevnic** [comment]
let's do the vendor/product and provider/service approach: amazon/ec2, amazon/s3, vmware/vcenter etc.

**Comment by tethryus** [comment]
PR https://github.com/CloudSlang/cloud-slang-content/pull/861 active, will be merged in WS_1_0 after review.

**Comment by Madalin-HPE** [comment]
@lrevnic Isn't Amazon the vendor, AWS the product, and EC2 the service? Why are we removing the product in the case of AWS?

**Comment by tethryus** [comment]
Content has been updated in the WS_1_0 branch with the changes required. The "cloud" folder has been decomissioned and the virtualization folder as well. It will be merged into the master branch and then closed, when the major PR will be reviewed and approved.

**Comment by tethryus** [comment]
Issue can be closed, since the requirements have been met. Content updated in WS_1_0 and master branch.
