### ISSUE TITLE
Cannot launch flow with SShShellCommandAction

### ISSUE THREAD

**Issue by FlorianJDF** [CloudSlang/cloud-slang-content#862]
Hello,

When trying to launch a simple flow using the SSH Command, I have the following error:

Command failed java.lang.RuntimeException: Slang Error: Method [runSshShellCommand] invocation of class [io.cloudslang.content.ssh.actions.SSHShellCommandAction] failed!!!!

Did anyone tested this operation lately or have an idea of why it is not working?

Thanks

**Comment by tethryus** [comment]
Hello @FlorianJDF The operations is tested at every build and it should work just fine. Are there any inputs you are not declaring that are required?

**Comment by Bonczidai** [comment]
@FlorianJDF did you manage to overcome the problem?

that's a general error message - in the logs you should find a specific one

my first guess would be a Maven related error (e.g. in `configuration/cslang.properties` Maven Central is used as remote repo, but you are in a corporate network )

**Comment by FlorianJDF** [comment]
The problem is that the cslang engine starts the maven check only the first time you start it.
So if you use the cslang engine, then break some maven dependencies, you'll have to launch maven by yourself in order to have every jar needed.
