### ISSUE TITLE
Sometimes confusing or strange as to what type an input should be.

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang-content#89]
@SamMarkowitz during bug hunt:
In the comparison\less_than_percentage operation the inputs are strings even though the operation is something you do to ints. Adds complexity of FAILURE result for no particularly good reason.

**Comment by tethryus** [comment]
@meshipeer Since this operation will be changed into a decision, how inputs are handled will still be considered an issue, or it can be closed?
