### ISSUE TITLE
default SSH operation to Brocade device unable to send commands to login shell

### ISSUE THREAD

**Issue by selenex** [CloudSlang/cloud-slang-content#964]
cslang>run myssh_op.sl --i "host=a.b.c.d,username=eng,password=xxxxxxxx,command=enable\r\n"

Operation outputs:
- return_result = Protocol error, doesn't start with scp!

- command_return_code = 0
- return_code = 0
- standard_out = Protocol error, doesn't start with scp!

Operation: icx_ssh finished with result: SUCCESS
Execution id: 101600015, duration: 0:00:01.420

(Logs of Brocade ICX)
Dynamic Log Buffer (50 lines):
Jan 23 13:44:24:I:Security: SSH logout by eng from src IP x.x.x.x from src     MAC abcd.efgh.ijkl from USER EXEC mode using RSA as Server Host Key.
 an 23 13:44:24:I:enable
Jan 23 13:44:24:I:Security: SSH login by eng from src IP x.x.x.x from src     MAC abcd.efgh.ijkl to USER EXEC mode using RSA as Server Host Key.

****
Expected behavior from a normal manual ssh login and issuing 'enable' is:
Jan 23 15:08:17:I:Security: SSH login by eng from src IP x.x.x.x from src MAC abcd.efgh.ijklto PRIVILEGED EXEC mode using RSA as Server Host Key.
Jan 23 15:08:12:I:Security: SSH login by eng from src IP x.x.x.x from src MAC abcd.efgh.ijkl to USER EXEC mode using RSA as Server Host Key.

The switch appears to interpret the Java operation as an SCP command, and does not process it as a shell command. 

This is the debug output from the switch:

telnet@ICX7750-48F Router#debug ip ssh
          SSH:  debugging is on
telnet@ICX7750-48F Router#SSH: ssh_get_free_session_id: ssh.client[0].in_use is 0
SSH[0]: ssh_is_connection_allowed..NEW CONNECTION
SSH[0]:ssh_socket_control: new connection
SSH[0]:ShtcpOpenPassive: WaitingForConnection (reusing)
SSH[0]:Awaiting child task init complete
SSH[0]:ssh_socket_control:Incoming connection ready
SSH:tcp incoming tcb 0x16fb457c, handle 0x16fb457c
SSH[0]: Data is ready to receive
SSH[0]:ShtcpConnectionStatus: connection established
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 20
SSH: eShSessionInit state
SSH[0]:ShtcpSend: eSendComplete: sent 24/24
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionExpectVersion state
SSH[4] Length of the buffer received is 20
SSH[0]:ShtcpSend: eSendComplete: sent 288/288
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 408
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionNegotiation state
SSH: eShSessionExpectClientNegotiation state
SSH: eShSessionKeyExchangeDhInit state
SSH: eShSessionExpectNewKeys state
SSH: eShSessionTerminate state
SSH[0] Length of the buffer received is 408
Not protected by hmac
ShProcessMessage: 20
kShMsgKexInit message received
Match: diffie-hellman-group1-sha1
Match: ssh-rsa
Match: aes128-ctr
Match: aes128-ctr
Match: hmac-sha1
Match: hmac-sha1
Match: none
Match: none
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 152
SSH: eShSessionKeyExchangeDhInit state
SSH: eShSessionExpectNewKeys state
SSH: eShSessionTerminate state
SSH[0] Length of the buffer received is 152
Not protected by hmac
ShProcessMessage: 30
kShMsgKexDhInit message received
SSH[0]:ShtcpSend: eSendComplete: sent 704/704
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 16
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionExpectNewKeys state
SSH: eShSessionTerminate state
SSH[0] Length of the buffer received is 16
Not protected by hmac
ShProcessMessage: 21
kShMsgNewKeys message received
SSH[0]:ShtcpSend: eSendComplete: sent 16/16
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 68
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionEncrypted state
SSH[0] Length of the buffer received is 68
HMac matched incoming packet
ShProcessMessage: 5
kShMsgServiceRequest message received
SSH[0]:ShtcpSend: eSendComplete: sent 52/52
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 84
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionEncrypted state
SSH[0] Length of the buffer received is 84
HMac matched incoming packet
ShProcessMessage: 50
kShMsgUserAuthRequest message received
Received: UserAuth user=eng service=ssh-connection method=none
SSH[0]:ShtcpSend: eSendComplete: sent 68/68
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: eStcpPending
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionEncrypted state
SSH[0] Length of the buffer received is 0
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 100
SSH: eShSessionEncrypted state
SSH[0] Length of the buffer received is 100
HMac matched incoming packet
ShProcessMessage: 50
kShMsgUserAuthRequest message received
Received: UserAuth user=eng service=ssh-connection method=password
SSH[0]:ShtcpSend: eSendComplete: sent 36/36
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 68
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionAuthenticated/eShSessionClosing state
SSH[0] Length of the buffer received is 68
HMac matched incoming packet
ShProcessMessage: 90
kShMsgChannelOpen message received
Received: Channel open channel=session
SSH[0]:ShtcpSend: eSendComplete: sent 52/52
SSH[0]: Data is ready to receive
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: string length 68
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH: eShSessionAuthenticated/eShSessionClosing state
SSH[0] Length of the buffer received is 68
HMac matched incoming packet
ShProcessMessage: 98
kShMsgChannelRequest message received
Received: Channel request 25: 12
 chan=6; request type=exec; want reply=1
ssh_event_handler : for session 0 (event 1).
SSH[0]:ssh_event_handler: listen event.
SSH[0]:ssh_event_handler: SCP
SSH[0]:ShtcpSend: eSendComplete: sent 36/36
ssh_event_handler : for session 0 (event 3).
SSH[0]:ssh_event_handler: Receive event.
ssh_parse_scp_cmd : length - 8
SSH[0]:***ssh_connection_task busy..return
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: eStcpPending
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH:ShHandleConnectionServices, fState 4
SSH: eShSessionAuthenticated/eShSessionClosing state
SSH[0]:ShtcpSend: eSendComplete: sent 84/84
SSH[0] Length of the buffer received is 0
SSH[0]:ShtcpReceiveStatus
SSH[0]:ShtcpReceiveStatus: eStcpPending
SSH[0]:ProcessPendingSend: send completion status=Complete, result=0
SSH:ShHandleConnectionServices, fState 4
ssh_event_handler : for session 0 (event 2).
SSH[0]:ssh_event_handler:Send event.

SSH:ssh_event_handler: Freeing tx_buf 41, QAddress: 18109d50
ssh_parse_scp_cmd_out : state - SSH_EXEC_CMD_OUT_COMPLETE (size = 0)
SSH[0]:ShtcpSend: eSendComplete: sent 140/140
ssh_event_handler : for session 0 (event 5).
SSH[0]:ssh_event_handler close/abort event.
SSH[0]: ssh_close_connection tcb_handle 0x16fb457c
ShFiniteStateMachine called for idle session state.
SSH[0]:***ssh_cleanup_session: no listener.
SSH[0]:ShtcpOpenPassive: WaitingForConnection
SSH[0]:ssh_child_itc_shutdown:tcb_handle 0x0
SSH[0]:***ssh_cleanup_session: no listener.
SSH: ssh_close_session# 0, No. of Clients# 0.
SSH: ssh_close_session# 0, No. of Out Clients# 0.

**Comment by andreivasiletruta** [comment]
@tethryus I am able to reproduce in the lab.
the message I get within the flow is the one mentioned by @selenex .
On the brocade device I seem to match to calls like:

`SSH[2]:ssh_event_handler: SCP
ssh_parse_scp_cmd : length - 1
ssh_parse_scp_cmd_out : state - SSH_EXEC_CMD_OUT_COMPLETE (size = 0)
SSH[2]:ssh_event_handler: SCP
ssh_parse_scp_cmd : length - 4
ssh_parse_scp_cmd_out : state - SSH_EXEC_CMD_OUT_COMPLETE (size = 0)`

**Comment by tethryus** [comment]
Hello @selenex I have a question regarding your flow, are you using a wrapper flow over ssh_flow.sl or ssh_command.sl?

In case you are using ssh_flow.sl try using ssh_command.sl and let me know if you encounter the same or any other issue.
